import type { Metadata } from "next";
import { Comfortaa, Geist_Mono } from "next/font/google";
import { ClientSessionProvider } from "~/providers/seesion-provider";
import { ThemeProvider } from "~/providers/theme-provider";
import "./globals.css";

const comfortaa = Comfortaa({
    variable: "--font-comfortaa",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${comfortaa.className} antialiased`}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <ClientSessionProvider>{children}</ClientSessionProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
